accounts/urls.py
from django.urls import include, path
from django.views.generic import TemplateView
from .views import (
    SignUpView, SignUpTmpReceptView, ActivateUserView,
    OverlapLoginView, OverlapLogoutView, TokenDeleteView,
    OverlapPasswordChangeView, OverlapPasswordChangeOneStepView, OverlapPasswordChangeDoneView,
    OverlapPasswordResetView, OverlapPasswordResetDoneView, OverlapPasswordResetConfirmView,
    EmailChangeView, EmailChangeTmpReceptView, ActivateEmailView,
    UserDeleteView, UserIdSetView,
)

app_name = 'accounts'

urlpatterns = [
    # サインアップ
    path('signup/',                    SignUpView.as_view(),          name='signup'),
    path('signup/tmp_recept/',         SignUpTmpReceptView.as_view(), name='signup_tmp_recept'),
    path('activate_user/<str:token>/', ActivateUserView,              name='activate_user'),
    # ユーザIDの設定
    path('signup/set_user_id', UserIdSetView.as_view(), name='uset_ser_id'),
    # ログイン/ログアウト処理
    path('login/',  OverlapLoginView.as_view(),  name='login'),
    path('logout/', OverlapLogoutView.as_view(), name='logout'),
    # パスワード変更
    path('password_change/',      OverlapPasswordChangeView.as_view(),        name='password_change'),
    path('password_change_/',     OverlapPasswordChangeOneStepView.as_view(), name='password_change_one_step'),
    path('password_change/done/', OverlapPasswordChangeDoneView.as_view(),    name='password_change_done'),
    # パスワード再設定
    path('password_reset/',         OverlapPasswordResetView.as_view(),        name='password_reset'),
    path('password_reset/done/',    OverlapPasswordResetDoneView.as_view(),    name='password_reset_done'),
    path('reset/<uidb64>/<token>/', OverlapPasswordResetConfirmView.as_view(), name='password_reset_confilm'),
    # メールアドレスの変更
    path('email_change/',               EmailChangeView.as_view(),          name='email_change'),
    path('email_change/tmp_recept/',    EmailChangeTmpReceptView.as_view(), name='email_change_tmp_recept'),
    path('activate_email/<str:token>/', ActivateEmailView,                  name='email_change_confilm'),
    # アカウントの削除
    path('delete/', UserDeleteView.as_view(), name='delete'),
    # # トークンの破棄(見の覚えのないメールが届いた方用)
    path('token_delete/<str:token>/', TokenDeleteView,                                                                name='token_delete'),
    path('token_delete_s/',           TemplateView.as_view(template_name='accounts/TokenDelete/delete_success.html'), name='token_delete_success'),
    path('token_delete_f/',           TemplateView.as_view(template_name='accounts/TokenDelete/delete_failure.html'), name='token_delete_failure'),
    # 外部 urls.py 参照
    path('', include('apps.user_properties.urls', namespace='user_properties')),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
     # admin
     path(settings.ADMIN_PATH+'/', admin.site.urls),
     # home
     path('', TemplateView.as_view(template_name='pages/home/home_base.html', extra_context={'IS_NO_USE_CONTEINER':True}), name='home'),
     # accounts
     path('accounts/', include('accounts.urls')),
     # apps
     path('inquiry/',   include('apps.inquiry.urls')),
     
     # 動作確認用サンプル
     path('sample/', include('sample.urls', namespace='sample')),
]
# ADD social-auth-app-django
if settings.IS_USE_SOCIAL_LOGIN:
     urlpatterns += [path('auth/', include('common.lib.social_django.urls', namespace='social')),]
# 内部から静的メディアファイルを配信するための設定
if not settings.IS_USE_GCS:
    import os
    from django.conf.urls.static import static
    from django.urls import re_path
    from django.views.static import serve
    # 内部 static を配信する
    urlpatterns += [ re_path(r'^static/(?P<path>.*)$', serve, {'document_root': os.path.join(settings.BASE_DIR, 'static/')}, name='static_urlpattern') ]
    urlpatterns += [ re_path(r'^media/(?P<path>.*)$',  serve, {'document_root': os.path.join(settings.BASE_DIR, 'media/')},  name='media_urlpattern') ]
    if settings.DEBUG:
        # media を利用
        urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)
        urlpatterns += [
            path('test_404/', TemplateView.as_view(template_name='404.html',)),
        ]

templates/apps/user_properties/asset/sidenav/sidenav.html
{% extends 'navbar.html' %}

{% block navber_include_sideber %}
{% if user.is_authenticated %}
<div id="SideNav">
    {# --- Displayed md or less --- #}
    <button class="btn d-lg-none" id='SideNavScrollLeftBtn'>
        <i class="fa-solid fa-angle-left"></i>
    </button>
    <ul class="list-group" id="SideNavScrollArea">
        <li class="pt-lg-2">
            <a class="list-group-item list-group-item-action {{ user_profile_active }}"
               href="{% url 'accounts:user_properties:user_profile' %}">
                <span>プロフィール</span>
            </a>
        </li>
        <li class="pt-lg-2">
            <a class="list-group-item list-group-item-action {{ user_reception_setting_active }}"
               href="{% url 'accounts:user_properties:user_reception_setting' %}">
               <span>受信設定</span>
            </a>
        </li>
        <li class="pt-lg-2">
            <a class="list-group-item list-group-item-action {{ email_change_active }}"
               href="{% url 'accounts:email_change' %}">
               <span>メールアドレスの変更</span>
            </a>
        </li>
        <li class="pt-lg-2">
            <a class="list-group-item list-group-item-action {{ password_change_active }}"
               href="{% if user.is_social_login and user.date_password_change is None %}{% url 'accounts:password_change_OneStep' %}{% else %}{% url 'accounts:password_change' %}{% endif %}">
               <span>パスワード変更</span>
            </a>
        </li>
        <li class="pt-lg-2">
            <a class="list-group-item list-group-item-action {{ delete_active }}"
               href="{% url 'accounts:delete' %}">
               <span>アカウントの閉鎖</span>
            </a>
        </li>
    </ul>
    {# --- Displayed md or less --- #}
    <button class="btn d-lg-none" id='SideNavScrollRightBtn'>
        <i class="fa-solid fa-angle-right"></i>
    </button>
</div>
{% endif %}
{% endblock %}